// <auto-generated />
namespace Contoso.Commerce.RetailProxy.Extension
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    
    /// <summary>
    /// Class implements Store Operations Manager.
    /// </summary>
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    internal class StoreOperationsManager : IStoreOperationsManager
    {
        private IContext context;

        /// <summary>
        /// Initializes a new instance of the <see cref="StoreOperationsManager"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public StoreOperationsManager(IContext context)
        {
            this.context = context;
        }
    
        
        /// <summary>
        /// OverrideCartLinePrice method.
        /// </summary>
        /// <param name="cartId">The cartId.</param>
        /// <param name="lineId">The lineId.</param>
        /// <param name="newPrice">The newPrice.</param>
        /// <returns>Cart object.</returns>
        public async Task<Cart> OverrideCartLinePrice(string cartId, string lineId, decimal newPrice)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<Cart>(
                "",
                "StoreOperations",
                "OverrideCartLinePrice",
                true, null, OperationParameter.Create("cartId", cartId, false),
                  OperationParameter.Create("lineId", lineId, false),
                  OperationParameter.Create("newPrice", newPrice, false));
        }
        
        /// <summary>
        /// SimplePingPost method.
        /// </summary>
        /// <returns>bool object.</returns>
        public async Task<bool> SimplePingPost()
        {       
            return await this.context.ExecuteOperationSingleResultAsync<bool>(
                "",
                "StoreOperations",
                "SimplePingPost",
                true, null);
        }
        
        /// <summary>
        /// GetOnlineShoppingCartList method.
        /// </summary>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Cart.</returns>
        public async Task<PagedResult<Cart>> GetOnlineShoppingCartList(QueryResultSettings queryResultSettings = null)
        {       
            return await this.context.ExecuteOperationAsync<Cart>(
                "",
                "StoreOperations",
                "GetOnlineShoppingCartList",
                true, queryResultSettings, null);
        }
        
        /// <summary>
        /// GetCartById method.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>Cart object.</returns>
        public async Task<Cart> GetCartById(string id)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<Cart>(
                "",
                "StoreOperations",
                "GetCartById",
                true, null, OperationParameter.Create("id", id, false));
        }
        
        /// <summary>
        /// SearchInventoryDocumentLine method.
        /// </summary>
        /// <param name="searchCriteria">The searchCriteria.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of InventoryInboundOutboundDocumentLine.</returns>
        public async Task<PagedResult<InventoryInboundOutboundDocumentLine>> SearchInventoryDocumentLine(InventoryDocumentLineSearchCriteria searchCriteria, QueryResultSettings queryResultSettings = null)
        {       
            return await this.context.ExecuteOperationAsync<InventoryInboundOutboundDocumentLine>(
                "",
                "StoreOperations",
                "SearchInventoryDocumentLine",
                true, queryResultSettings, null, OperationParameter.Create("searchCriteria", searchCriteria, false));
        }
        
        /// <summary>
        /// SimplePingGet method.
        /// </summary>
        /// <returns>bool object.</returns>
        public async Task<bool> SimplePingGet()
        {       
            return await this.context.ExecuteOperationSingleResultAsync<bool>(
                "",
                "StoreOperations",
                "SimplePingGet",
                false, null);
        }
        
    }
    
    /// <summary>
    /// Class implements ExampleEntity Manager.
    /// </summary>
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    internal class ExampleEntityManager : IExampleEntityManager
    {
        private IContext context;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExampleEntity"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public ExampleEntityManager(IContext context)
        {
            this.context = context;
        }

        /// <summary>
        /// Creates the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns>The updated entity after creation.</returns>
        public async Task<ExampleEntity> Create(ExampleEntity entity)
        {
            return await this.context.Create<ExampleEntity>("BoundController", entity);
        }

        /// <summary>
        /// Reads the entity with specified identifier.
        /// </summary>
        /// <param name="unusualEntityId">The unusualEntityId.</param>
        /// <param name="expandProperties">The navigation properties to be expanded.</param>
        /// <returns>The entity.</returns>
        public async Task<ExampleEntity> Read(long unusualEntityId, ICollection<string> expandProperties = null)
        {
            return await this.context.Read<ExampleEntity>(
                    "BoundController",
                    e => e.UnusualEntityId == unusualEntityId,
                    expandProperties,
                    OperationParameter.Create("UnusualEntityId", unusualEntityId, true));
        }
      
        /// <summary>
        /// Read all entities with specified query settings.
        /// </summary>
        /// <param name="queryResultSettings">The query result settings.</param>
        /// <param name="expandProperties">The navigation properties to be expanded.</param>
        /// <returns>The collection of entities.</returns>
        public async Task<PagedResult<ExampleEntity>> ReadAll(QueryResultSettings queryResultSettings, ICollection<string> expandProperties = null)
        {
            return await this.context.ReadAll<ExampleEntity>("BoundController", expandProperties, queryResultSettings);
        }

        /// <summary>
        /// Updates the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns>The updated entity.</returns>
        public async Task<ExampleEntity> Update(ExampleEntity entity)
        {
            return await this.context.Update<ExampleEntity>("BoundController", entity);
        }

        /// <summary>
        /// Deletes the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns>No return.</returns>
        public async Task Delete(ExampleEntity entity)
        {
            await this.context.Delete<ExampleEntity>("BoundController", entity);
        }
        
        // Operations
        
        /// <summary>
        /// CreateExampleEntity method.
        /// </summary>
        /// <param name="entityData">The entityData.</param>
        /// <returns>long object.</returns>
        public async Task<long> CreateExampleEntity(ExampleEntity entityData)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<long>(
                "BoundController",
                "ExampleEntity",
                "CreateExampleEntity",
                true, null, OperationParameter.Create("entityData", entityData, false));
        }
        
        /// <summary>
        /// UpdateExampleEntity method.
        /// </summary>
        /// <param name="unusualEntityId">The unusualEntityId.</param>
        /// <param name="updatedEntity">The updatedEntity.</param>
        /// <returns>bool object.</returns>
        public async Task<bool> UpdateExampleEntity(long unusualEntityId, ExampleEntity updatedEntity)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<bool>(
                "BoundController",
                "ExampleEntity",
                "UpdateExampleEntity",
                true, null, OperationParameter.Create("UnusualEntityId", unusualEntityId, true),
                OperationParameter.Create("updatedEntity", updatedEntity, false));
        }
        
        /// <summary>
        /// DeleteExampleEntity method.
        /// </summary>
        /// <param name="unusualEntityId">The unusualEntityId.</param>
        /// <returns>bool object.</returns>
        public async Task<bool> DeleteExampleEntity(long unusualEntityId)
        {       
            return await this.context.ExecuteOperationSingleResultAsync<bool>(
                "BoundController",
                "ExampleEntity",
                "DeleteExampleEntity",
                true, null, OperationParameter.Create("UnusualEntityId", unusualEntityId, true));
        }
        
        /// <summary>
        /// GetAllExampleEntities method.
        /// </summary>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of ExampleEntity.</returns>
        public async Task<PagedResult<ExampleEntity>> GetAllExampleEntities(QueryResultSettings queryResultSettings = null)
        {       
            return await this.context.ExecuteOperationAsync<ExampleEntity>(
                "BoundController",
                "ExampleEntity",
                "GetAllExampleEntities",
                false, queryResultSettings, null);
        }
        
    }
    
 }
