// <auto-generated />
namespace Contoso.Commerce.RetailProxy.Extension
{
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using Microsoft.Dynamics.Commerce.RetailProxy;
    using Microsoft.Dynamics.Commerce.RetailProxy.Adapters;
    using Microsoft.OData.Client;
    
    /// <summary>
    /// ExampleEntity entity class.
    /// </summary>
    [Microsoft.OData.Client.Key("UnusualEntityId")]
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    public class ExampleEntity : CommerceEntity
    { 
        /// 
        /// Initializes a new instance of the <see cref="ExampleEntity" /> class.
        /// 
        public ExampleEntity()
        {
            
            this._extensionProperties.CollectionChanged += ExtensionProperties_OnCollectionChanged;
        }
      
        /// <summary>
        /// Gets or sets the IntData.
        /// </summary>
        public int IntData
        {
            get
            {
                return this._intData;
            }
        
            set
            {
                this._intData = value;
                this.OnPropertyChanged("IntData");
            }
        }
      
        private int _intData;
      
        /// <summary>
        /// Gets or sets the StringData.
        /// </summary>
        public string StringData
        {
            get
            {
                return this._stringData;
            }
        
            set
            {
                this._stringData = value;
                this.OnPropertyChanged("StringData");
            }
        }
      
        private string _stringData;
      
        /// <summary>
        /// Gets or sets the UnusualEntityId.
        /// </summary>
        public long UnusualEntityId
        {
            get
            {
                return this._unusualEntityId;
            }
        
            set
            {
                this._unusualEntityId = value;
                this.OnPropertyChanged("UnusualEntityId");
            }
        }
      
        private long _unusualEntityId;
      
        /// <summary>
        /// Gets or sets the ExtensionProperties.
        /// </summary>
        public ObservableCollection<CommerceProperty> ExtensionProperties
        {
            get
            {
                return this._extensionProperties;
            }
        
            set
            {
                this._extensionProperties = value;
                this.OnPropertyChanged("ExtensionProperties");
            }
        }
      
        private void ExtensionProperties_OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnPropertyChanged("ExtensionProperties");  
        }
    
        private ObservableCollection<CommerceProperty> _extensionProperties = new ObservableCollection<CommerceProperty>();
      
    }
    
}
  