// <auto-generated />
namespace Contoso.Commerce.RetailProxy.Extension.Adapters
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.IO;
    using System.Threading.Tasks;

    
    /// <summary>
    /// Interface for Store Operations Manager.
    /// </summary>
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    public interface IStoreOperationsManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// OverrideCartLinePrice method.
        /// </summary>
        /// <param name="cartId">The cartId.</param>
        /// <param name="lineId">The lineId.</param>
        /// <param name="newPrice">The newPrice.</param>
        /// <returns>Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart object.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart> OverrideCartLinePrice(string cartId, string lineId, decimal newPrice);
    
        /// <summary>
        /// SimplePingPost method.
        /// </summary>
        /// <returns>bool object.</returns>
        Task<bool> SimplePingPost();
    
        /// <summary>
        /// GetOnlineShoppingCartList method.
        /// </summary>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart>> GetOnlineShoppingCartList(Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
        /// <summary>
        /// GetCartById method.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart object.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.DataModel.Cart> GetCartById(string id);
    
        /// <summary>
        /// SearchInventoryDocumentLine method.
        /// </summary>
        /// <param name="searchCriteria">The searchCriteria.</param>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Microsoft.Dynamics.Commerce.Runtime.DataModel.InventoryInboundOutboundDocumentLine.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Microsoft.Dynamics.Commerce.Runtime.DataModel.InventoryInboundOutboundDocumentLine>> SearchInventoryDocumentLine(Microsoft.Dynamics.Commerce.Runtime.DataModel.InventoryDocumentLineSearchCriteria searchCriteria, Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
        /// <summary>
        /// SimplePingGet method.
        /// </summary>
        /// <returns>bool object.</returns>
        Task<bool> SimplePingGet();
    
    }
    
    /// <summary>
    /// Interface for ExampleEntity Manager.
    /// </summary>
    [GeneratedCodeAttribute("Contoso.Commerce.RetailProxy.Extension", "1.0")]
    public interface IExampleEntityManager : Microsoft.Dynamics.Commerce.RetailProxy.IEntityManager
    {
        
        /// <summary>
        /// CreateExampleEntity method.
        /// </summary>
        /// <param name="entityData">The entityData.</param>
        /// <returns>long object.</returns>
        Task<long> CreateExampleEntity(Contoso.CommerceRuntime.DataModel.ExampleEntity entityData);
    
        /// <summary>
        /// UpdateExampleEntity method.
        /// </summary>
        /// <param name="unusualEntityId">The unusualEntityId.</param>
        /// <param name="updatedEntity">The updatedEntity.</param>
        /// <returns>bool object.</returns>
        Task<bool> UpdateExampleEntity(long unusualEntityId, Contoso.CommerceRuntime.DataModel.ExampleEntity updatedEntity);
    
        /// <summary>
        /// DeleteExampleEntity method.
        /// </summary>
        /// <param name="unusualEntityId">The unusualEntityId.</param>
        /// <returns>bool object.</returns>
        Task<bool> DeleteExampleEntity(long unusualEntityId);
    
        /// <summary>
        /// GetAllExampleEntities method.
        /// </summary>
        /// <param name="queryResultSettings">The queryResultSettings.</param>
        /// <returns>Collection of Contoso.CommerceRuntime.DataModel.ExampleEntity.</returns>
        Task<Microsoft.Dynamics.Commerce.Runtime.PagedResult<Contoso.CommerceRuntime.DataModel.ExampleEntity>> GetAllExampleEntities(Microsoft.Dynamics.Commerce.Runtime.DataModel.QueryResultSettings queryResultSettings = null);
    
    }
    
 }
